# Generated by Django 6.0.1 on 2026-02-03 21:15

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True)),
                ('tareas_clientes', models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Client)'), (4, 'Stadistics access'), (5, 'Boss can create and modify clients and supervisors'), (6, 'Supervisor can create and modify clients only'), (7, 'Supervisor as client (Only modify status)')], default=0)),
                ('tareas_supervisor', models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Client)'), (4, 'Stadistics access'), (5, 'Boss can create and modify clients and supervisors'), (6, 'Supervisor can create and modify clients only'), (7, 'Supervisor as client (Only modify status)')], default=0)),
                ('estadisticas', models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Client)'), (4, 'Stadistics access'), (5, 'Boss can create and modify clients and supervisors'), (6, 'Supervisor can create and modify clients only'), (7, 'Supervisor as client (Only modify status)')], default=0)),
                ('modificar_usuarios', models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Client)'), (4, 'Stadistics access'), (5, 'Boss can create and modify clients and supervisors'), (6, 'Supervisor can create and modify clients only'), (7, 'Supervisor as client (Only modify status)')], default=0)),
                ('msg_cliente', models.BooleanField(default=False)),
                ('msg_supervisor', models.BooleanField(default=False)),
                ('msg_jefe', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_asignado', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor - Cliente',
                'verbose_name_plural': 'Supervisor - Clientes',
                'db_table': 'supervisor_clientes',
            },
        ),
        migrations.CreateModel(
            name='userRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'db_table': 'user_roles',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
