# Generated by Django 6.0.1 on 2026-02-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='msg_cliente',
            new_name='msg_empleado',
        ),
        migrations.RemoveField(
            model_name='role',
            name='tareas_clientes',
        ),
        migrations.AddField(
            model_name='role',
            name='tareas_empleados',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Employees)'), (4, 'Stadistics access'), (5, 'Boss can create and modify Employees and supervisors'), (6, 'Supervisor can create and modify employees only'), (7, 'Supervisor as employee (Only modify status)')], default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='estadisticas',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Employees)'), (4, 'Stadistics access'), (5, 'Boss can create and modify Employees and supervisors'), (6, 'Supervisor can create and modify employees only'), (7, 'Supervisor as employee (Only modify status)')], default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='modificar_usuarios',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Employees)'), (4, 'Stadistics access'), (5, 'Boss can create and modify Employees and supervisors'), (6, 'Supervisor can create and modify employees only'), (7, 'Supervisor as employee (Only modify status)')], default=0),
        ),
        migrations.AlterField(
            model_name='role',
            name='tareas_supervisor',
            field=models.IntegerField(choices=[(0, 'No access'), (1, 'View only'), (2, 'Can create and modify all tasks and status'), (3, 'Can modify just status tasks (Employees)'), (4, 'Stadistics access'), (5, 'Boss can create and modify Employees and supervisors'), (6, 'Supervisor can create and modify employees only'), (7, 'Supervisor as employee (Only modify status)')], default=0),
        ),
        migrations.CreateModel(
            name='SupervisorEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor_asignado', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleados_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supervisor - Empleado',
                'verbose_name_plural': 'Supervisor - Empleados',
                'db_table': 'supervisor_empleado',
            },
        ),
        migrations.DeleteModel(
            name='SupervisorCliente',
        ),
    ]
