# Generated by Django 6.0.1 on 2026-02-09 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_msg_cliente_role_msg_empleado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='msg_empleado',
        ),
        migrations.RemoveField(
            model_name='role',
            name='msg_jefe',
        ),
        migrations.RemoveField(
            model_name='role',
            name='msg_supervisor',
        ),
    ]
