# Generated by Django 6.0.1 on 2026-02-03 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_REVISION', 'Pendiente de revisión'), ('FINALIZADA', 'Finalizada'), ('NO_COMPLETADA', 'No Completada')], default='PENDIENTE', max_length=20)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('reabierta', models.BooleanField(default=False)),
                ('aprobada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('asignado_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('asignado_original', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_reabiertas_previas', to=settings.AUTH_USER_MODEL)),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['-creada_en'],
            },
        ),
    ]
