# Generated by Django 6.0.1 on 2026-02-10 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
